config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/events/:id/tickets', to: 'events#event_tickets'

  resources :events, :only => [:index, :new, :create, :update, :edit]
  resources :tickets
  resources :users

  root :to => "static_pages#home"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets
  validates :artist, presence: {message: "Proszę podać nazwę artysty/wydarzenia"}
  validates :tickets_no, :presence => true
  validates :tickets_no, numericality: {only_integer: true, greater_than: 0, message: "Nie może być mniej niż 1 bilet w wydarzeniu"}
  validates :price_high, :presence => true
  validates :price_high, numericality: {greater_than_or_equal_to: :price_low, message: "Cena nie może być mniejsza od najniższej ceny"}
  validates :price_low, :presence => true
  validates :price_low, numericality: { greater_than_or_equal_to: 0, message: "Cena nie może być mniejsza od 0 zł"}
  validates :event_date, :presence => true
#  validate :valid_date?
  validate :event_date_cannot_be_in_the_past

  def event_date_cannot_be_in_the_past
    if event_date.present? && event_date < Date.today
      errors.add(:event_date, 'Wydarzenie nie może być w przeszłości.')
    end
  end

  def valid_date?
    if event_date.present?
      if (Date.strptime(event_date, '%d-%m-%Y') rescue nil).nil?
        errors.add(:event_date, 'Zły format daty, powinien być: dd-mm-yyyy')
      end
    end
  end

  def artist_and_date
    "#{artist}, #{event_date}"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update]

  def index
    if is_admin?
      @events = Event.all.order('artist', 'event_date')
    else
      @events = Event.where('event_date >= ?', Date.today).order('artist', 'event_date')
    end

  end

  def event_tickets
    if is_admin?
      set_event
      @tickets = Ticket.where('event_id = ?', params[:id])
    else
      respond_to do |format|
        format.html { redirect_to static_pages_home_path, notice: 'Nie posiadasz odpowiednich praw.' }
        format.json { head :no_content }
      end
    end

  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:info] = 'Event został poprawnie stworzony.'
      redirect_to events_path
    else
      render :action => "new"
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Wydarzenie zostało zaktualizowane.' }
        format.json { render :show, status: :ok, location: events_path }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_event
    begin
      @event = Event.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @event = nil
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:artist, :event_date, :price_low, :price_high, :description, :for_adults, :tickets_no)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
    <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :artist %>
      <%= f.text_field :artist %>
    </div>

    <div class="field">
      <%= f.label :for_adults %>
      <%= f.check_box :for_adults, {}, true, false %>
    </div>

    <div class="field">
      <%= f.label :event_date %>
      <%= f.text_field :event_date %>
    </div>

    <div class="field">
      <%= f.label :price_low %>
      <%= f.text_field :price_low %>
    </div>

    <div class="field">
      <%= f.label :price_high %>
      <%= f.text_field :price_high %>
    </div>

    <div class="field">
      <%= f.label :tickets_no %>
      <%= f.text_field :tickets_no %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<h1>Edytuj wydarzenie</h1>

<%= render 'form', event: @event %>

<%= link_to 'Wydarzenie', @event %> |
<%= link_to 'Powrót', events_path %>

app/views/events/event_tickets.html.erb
<div class="container">
  <% if @tickets.nil? || @event.nil? %>
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h2 class="h2">Brak wydarzenia</h2>
        </div>
        <div class=" text-info panel-body">
          <h3>Wydarzenie o podanym id nie istnieje</h3>
        </div>
      </div>
  <% else %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <h2 class="h2" style="margin-left:20px"><strong> Wydarzenie:</strong>
              <%= @event.artist %>, <%= @event.event_date %>
              <%= link_to 'Wydarzenia', events_path, class: 'btn btn-info pull-right', style: 'margin-right: 20px;' %>
            </h2>

          </div>
        </div>
        <div class="panel-body">
          <table class="table table-responsive">
            <thead>
            <tr>
              <th>Nazwa</th>
              <th>Miejsce</th>
              <th>Adres</th>
              <th>Cena</th>
              <th>Email</th>
              <th>Phone</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% if @tickets.size > 0 %>
                <% @tickets.each do |ticket| %>
                    <tr>
                      <td><%= ticket.name %></td>
                      <td><%= ticket.seat_id_seq %></td>
                      <td><%= ticket.address %></td>
                      <td><%= ticket.price %></td>
                      <td><%= ticket.email_address %></td>
                      <td><%= ticket.phone %></td>
                    </tr>
                <% end %>
            <% end %>

            </tbody>
          </table>
        </div>
      </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h1>Wydarzenia</h1>

    </div>
    <div class="panel-body">
      <table class="table table-responsive">
        <thead>
        <tr>
          <th>Id</th>
          <th>Nazwa artysty</th>
          <th>Data wydarzenia</th>
          <th>Dla dorosłych</th>
          <th>Ceny</th>
          <th>Sprzedane/Liczba biletów</th>

        </tr>
        </thead>

        <tbody>
        <% @events.each do |event| %>
            <tr>
              <td><%= event.id %></td>
              <td><%= event.artist %></td>
              <td><%= event.event_date %></td>
              <td><%= event.for_adults %></td>
              <td><%= event.price_low %>-<%= event.price_high %></td>
              <td><%= Ticket.where('event_id = ?', event.id).count %>/<%= event.tickets_no %></td>
              <% if is_admin? %>
                  <td>
          <span class="btn-group btn-group-sm">
            <% if Ticket.where('event_id = ?', event.id).count > 0 %>
            <%= link_to 'Sprzedane bilety', url_for('events/'+ event.id.to_s + '/tickets'), :class => "btn btn-sm btn-default" %>
            <% end %>
            <%= link_to 'Edytuj', edit_event_path(event), :class => "btn btn-sm btn-primary" %>
          </span>
                  </td>
              <% end %>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br>
      <% if is_admin? %>
          <div class="  btn-group">
            <div class="btn btn-info"><%= link_to 'Nowe wydarzenie', new_event_path %></div>
            <div class="btn btn-default"><%= link_to 'Sprzedane bilety', tickets_path %></div>
          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/events/new.html.erb
<h1>Dodaj nowe wydarzenie:</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>