config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/events/:id/tickets', to: 'events#event_tickets'

  resources :events, :only => [:index, :new, :create, :update, :edit]
  resources :tickets
  resources :users

  root :to => "static_pages#home"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  validates :name, :presence => true
  # validates :name, :uniqueness => true
  validates :email_address, :presence => true
  validate :less_than_5_tickets
  validate :seat_is_taken
  validates :price, :presence => true
  validate :price_between_min_max

  def less_than_5_tickets
    tickets = Ticket.where('event_id = ? and email_address = ?', event_id, email_address)
    if tickets.size >= 5 and not(tickets.pluck(:id).include? id)
      errors.add(:email_address, 'Można zamówić maksymalnie 5 biletów na dane wydarzenie.')
    end
  end

  def seat_is_taken
    ticket = Ticket.where('event_id = ? and seat_id_seq = ?', event_id, seat_id_seq)
    if ticket and id != ticket.pluck(:id).first
      errors.add(:seat_id_seq, 'Wybrane miejsce jest już zajęte na to wydarzenie.')
    end
  end

  def price_between_min_max
    event = Event.find(event_id)
    if price.to_i < event.price_low.to_i or price.to_i > event.price_high.to_i
      errors.add(:price, 'Cena musi zawierać się w przedziale %d - %d' % [event.price_low, event.price_high])
    end
  end

  def price_arr
    event = Event.find(event_id)
    if event.event_date == Date.today
      event.price_high = 1.2 * event.price_high
    end
    return (event.price_low..event.price_high).step(70)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    if is_admin?
      @tickets = Ticket.all
    else
      respond_to do |format|
        format.html { redirect_to static_pages_home_path, notice: 'Nie posiadasz odpowiednich praw.' }
        format.json { head :no_content }
      end
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
      set_ticket
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Bilet został zaktualizowany.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    begin
      @ticket = Ticket.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @event = nil
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(ticket) do |f| %>
    <% if ticket.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

          <ul>
            <% ticket.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :event_id %>
      <%= f.collection_select :event_id,  Event.where('event_date >= ? and event_date <= ? ', Date.today, Date.today + 30), :id, :artist_and_date%>
    </div>

    <div class="field">
      <%= f.label :seat_id_seq %>
      <%= f.text_field :seat_id_seq %>
    </div>

    <div class="field">
      <%= f.label :address %>
      <%= f.text_area :address %>
    </div>

    <div class="field">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>

    <div class="field">
      <%= f.label :email_address %>
      <%= f.text_field :email_address %>
    </div>

    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Bilet', @ticket %> |
<%= link_to 'Powrót', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h1>Bilety</h1>
    </div>
    <div class="panel-body">
      <table class="table table-responsive">
        <thead>
        <tr>
          <th>Nazwa</th>
          <th>Wydarzenie</th>
          <th>Miejsce</th>
          <th>Adres</th>
          <th>Cena</th>
          <th>Email</th>
          <th>Phone</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @tickets.each do |ticket| %>
            <tr>
              <td><%= ticket.name %></td>
              <td><%= Event.find(ticket.event_id).artist %>, <%= Event.find(ticket.event_id).event_date %></td>
              <td><%= ticket.seat_id_seq %></td>
              <td><%= ticket.address %></td>
              <td><%= ticket.price %></td>
              <td><%= ticket.email_address %></td>
              <td><%= ticket.phone %></td>
              <td>
          <span class="btn-group btn-group-sm">
            <%= link_to 'Show', ticket, :class => "btn btn-sm btn-default" %>
            <%= link_to 'Edit', edit_ticket_path(ticket), :class => "btn btn-sm btn-primary" %>
            <%= link_to link_to 'Destroy', ticket, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-sm btn-danger" %>

          </span>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br>
      <div class="btn-group">
        <%= link_to 'Nowy bilet', new_ticket_path, :class => "btn btn-info" %>
        <%= link_to 'Wydarzenia', events_path, :class => "btn btn-default" %>
      </div>

    </div>
  </div>
</div>

app/views/tickets/new.html.erb
<h1>Dodaj nowy bilet:</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<div class="container">
  <div class="panel panel-info">
    <% if @ticket.nil? %>
        <div class="panel-heading">
          <h2 class="h2"> Wolny bilet</h2>
        </div>
        <div class=" text-info panel-body">
          <h3>Bilet o podanym id jest wolny</h3>
        </div>
    <% else %>
        <div class="panel-heading">
          <h2 class="h2">Bilet : <%= @ticket.name %></h2>
        </div>
        <div class="panel-body">
          <p id="notice"><%= notice %></p>

          <div class="col-md-6">
            <h3>
              <strong>Wydarzenie:</strong>
              <%= (Event.find @ticket.event_id).artist %>, <%= (Event.find @ticket.event_id).event_date %>
            </h3>
            <h3>
              <strong>Nazwa:</strong>
              <%= @ticket.name %>
            </h3>
            <h3>
              <strong>Numer siedzenia:</strong>
              <%= @ticket.seat_id_seq %>
            </h3>
          </div>
          <div class="col-md-6">
            <h3>
              <strong>Adres:</strong>
              <%= @ticket.address %>
            </h3>
            <h3>
              <strong>Cena:</strong>
              <%= @ticket.price %>
            </h3>
            <h3>
              <strong>Email:</strong>
              <%= @ticket.email_address %>
            </h3>
            <h3>
              <strong>Numer telefonu:</strong>
              <%= @ticket.phone %>
            </h3>
          </div>

          <div class="btn-group">
            <% if logged_in? %>
                <div class="btn btn-warning">
                  <%= link_to 'Edit', edit_ticket_path(@ticket) %>
                </div>
                <div class="btn btn-default">
                  <%= link_to 'Back', tickets_path %>
                </div>
                </div>
            <% end %>

            </div>
    <% end %>
  </div>
</div>